const GET_USER_JOKES = 'GET_USER_JOKES';
const CREATE_JOKE = 'CREATE_JOKE';
const CREATE_JOKE_ERROR = 'CREATE_JOKE_ERROR';
const CREATE_JOKE_FINISHED = 'CREATE_JOKE_FINISHED';

export {
  GET_USER_JOKES,
  CREATE_JOKE,
  CREATE_JOKE_ERROR,
  CREATE_JOKE_FINISHED
};
