const GET_USER_JOKES = 'GET_USER_JOKES';
const GET_USER_JOKES_SUCCESS = 'GET_USER_JOKES_SUCCESS';
const GET_USER_JOKES_ERROR = 'GET_USER_JOKES_ERROR';
const CREATE_JOKE = 'CREATE_JOKE';
const CREATE_JOKE_ERROR = 'CREATE_JOKE_ERROR';
const CREATE_JOKE_FINISHED = 'CREATE_JOKE_FINISHED';
const RESET_LOADING_STATE = 'RESET_LOADING_STATE';

export {
  GET_USER_JOKES,
  GET_USER_JOKES_SUCCESS,
  GET_USER_JOKES_ERROR,
  CREATE_JOKE,
  CREATE_JOKE_ERROR,
  CREATE_JOKE_FINISHED,
  RESET_LOADING_STATE
};
